Fix str exception raised in LibratoConnection
When librato connection is None for example, the ``__init__`` method of the LibratoConnection object raises an "str" exception.

It leads the python interpreter to throw an exception:

```python
/mysupperdupperenv/lib/python2.7/site-packages/librato/__init__.pyc in __init__(self, username, api_key, hostname, base_path)
     73       self.api_key   = api_key.encode('ascii')
     74     except:
---> 75       raise("Librato only supports ascii for the credentials")
     76
     77     self.hostname      = hostname

TypeError: exceptions must be old-style classes or derived from BaseException, not str
```

This fix leads ``__init__`` method to throw a *TypeError* instead.